service: b

custom:
  parcel:
    bundleNodeModules: true

plugins:
  - serverless-plugin-parcel

provider:
  name: aws
  runtime: nodejs12.x

functions:
  func-b:
    handler: src/b.handler
    events:
      - http:
          method: get
          path: /
